---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: knative-serving
  namespace: openshift-operators
spec:
  channel: techpreview
  source: redhat-operators-packages
  name: serverless-operator
  sourceNamespace: openshift-operators